# https://distribution.github.io/distribution/about/configuration/
version: 0.1
log:
  level: debug
  formatter: text
  fields:
    service: registry
  # hooks:
    # - type: mail
      # levels:
        # - panic
      # options:
        # smtp:
          # addr: smtp.sendhost.com:25
          # username: sendername
          # password: password
          # insecure: true
        # from: name@sendhost.com
        # to:
          # - name@receivehost.com
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  # azure:
  # gcs:
  # s3:
  # inmemory:
  cache:
    blobdescriptor: inmemory
auth:
  ## dev
  # silly:
    # realm: silly-realm
    # service: silly-service
  ## jwt token
  # token:
    # realm: token-realm
    # service: token-service
    # issuer: registry-token-issuer
    # rootcertbundle: /root/certs/bundle
    # jwks: /path/to/jwks
    # signingalgorithms:
        # - EdDSA
        # - HS256
        # - ES512
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
