apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJmb3JtYXRpb24ubGFuOjQ0MyI6IHsKCQkJImF1dGgiOiAiZEdWemRIVnpaWEk2Y0dGemMzZHZjbVE9IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  namespace: stack-java
  name: regcred
type: kubernetes.io/dockerconfigjson
