apiVersion: apps/v1
kind: Deployment
# méta du dpl
metadata:
  namespace: stack-java
  labels:
    app: sample-java
  name: sample-java
  # annotations:
  #   kubernetes.io/change-cause: "upgrade 1.1"
    
# contenu du dpl
spec:
  # le nb de pods repliqués
  replicas: 2
  # CONDITION D'ASSOCIATION ENTRE DPL <=> POD
  selector:
    # association via les labels app=sample-java dans le dpl et le pod
    matchLabels:
      app: sample-java
  # stratégie de MAJ => "Roling Update" par défaut
  strategy: {}
  # desciption du pod associé au dpl
  template:
    metadata:
      labels:
        app: sample-java
    # descritpion du contenu du pod associé au dpl
    spec:
      containers:
      # - image: jenkins.lan:443/stack-java-httpd:1.0
      #   name: stack-java-httpd
      #   imagePullPolicy: Always
      - image: jenkins.lan:443/stack-java-tomcat:1.1
        name: stack-java-tomcat
        # exposition au sens docker
        ports:
          - name: http
            containerPort: 8080
      imagePullSecrets:
      - name: regcred
