apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-java
  name: sample-java
  namespace: stack-java
spec:
  ports:
    # port du service = container (processus): qui redirige un flux
  - port: 80
    protocol: TCP
    # port du pod
    targetPort: http
  # association service <=> déploiement
  selector:
    app: sample-java
  # type: NodePort
  type: LoadBalancer
