---

## 1/ si l'image existe en local => pas de pull, pas de build
## 2/ si //            pas //    => pull sauf si les couches sont dans le cache, pas de build
## 3/ sinon en ajoutant docker compose up -d --build => force le build
## 4/ pas d'image en local , pas de registre (pricé ou public => DOCKER HUB) => build

networks:
  stack-java:
    name: stack-java
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1

services:
  httpd:
    container_name: stack-java-httpd 
    image: jenkins.lan:443/stack-java-httpd:1.0
    # build:
    #   context: ./httpd
    restart: unless-stopped
    networks:
      - stack-java
    ports:
      - 8081:80
    depends_on:
      - tomcat

  tomcat:
    container_name: stack-java-tomcat
    image: jenkins.lan:443/stack-java-tomcat:1.0
    ## on utilise pas le build docker compose dans un orchestrateur (swarm)
    # build:
    #   context: ./tomcat
    #   # no_cache: true
    #   args:
    #     - TOMCAT_VERSION_MAJOR=${TOMCAT_VERSION_MAJOR:-9}
    #     - TOMCAT_VERSION_FULL=${TOMCAT_VERSION_FULL:-9.0.98}
    restart: unless-stopped
    networks:
      - stack-java